# Copyright 2020 Toyota Research Institute.  All rights reserved.

# Config for training the v2 model:
#    - IONet
#    + descriptor upsampling
#    + cross-border keypoints
#    + descriptor loss
# Note: this uses a ResNet-based backbone.

arch:
  epochs: 10  # 绰绰有余

model:
  params:
    use_color: True
    do_upsample: True
    do_cross: True
    descriptor_loss: True
    use_new_descriptor_loss: True
    add_score_addition_loss: True
    add_desc_relate_score_loss: False
    keypoint_net_type: 'KeypointPreactResnet'
    train_which_desc: 'netvlad'
  scheduler:
    decay: 0.8
    lr_epoch_divide_frequency: 1
  optimizer:
    learning_rate: 0.001

datasets:
  augmentation:
    image_shape: (256,320)
    jittering: (0.4, 0.3, 0.3, 0.1)     # Color jittering values
  train:
    batch_size: 1
    num_workers: 0

wandb:
  dry_run: False
  project: "kp2d"